### ISSUE TITLE
main does not compile: PR #1's merge dropped diff.rs's storage-schema/duplicate-detection functions

### ISSUE THREAD

**Issue by Anuoluwapo25** [ShippedLabs/soroban-upgrade-safeguard#417]
## Summary

`origin/main` at `1b434fb` (and its parent `84fb5a1`, the merge of PR #1 / `fix/type-identity-and-event-classification`) does not compile. `cargo check` fails with 8 errors; `cargo check --all-targets` fails with more.

## Root cause

Before PR #1 merged, `src/diff.rs` on `main` (commit `e575dfd`) was **3050 lines** and defined a storage-schema/duplicate-detection diffing engine used by `lib.rs`, `report.rs`, and `dependency.rs`:

- `diff::compare_with_policy`
- `diff::compare_storage_schemas`
- `diff::report_duplicate_spec_entries`
- `diff::report_unresolved_storage_references`
- `diff::STORAGE_CATEGORY_PREFIX`, `diff::STORAGE_UNRESOLVED_CATEGORY`

PR #1's branch (`fix/type-identity-and-event-classification`) had its own independent rewrite of `diff.rs` (1888 lines, adding the type-identity/event-classification split) based on an older ancestor that predated the storage-schema work.

When PR #1 was merged into `main` at `84fb5a1`, the merge resolution kept the *branch's* `diff.rs` wholesale instead of reconciling it with `main`'s. The result: `main`'s `diff.rs` reverted to 1888 lines, silently dropping every storage-schema/duplicate-detection function — while `lib.rs`, `report.rs`, and `dependency.rs` (which merged correctly) still call them.

## Reproduction

```
git fetch origin main
git worktree add /tmp/main-check origin/main --detach
cd /tmp/main-check
cargo check
```

```
error[E0432]: unresolved imports `crate::diff::STORAGE_CATEGORY_PREFIX`, `crate::diff::STORAGE_UNRESOLVED_CATEGORY`
 --> src/report.rs:2:36
error[E0425]: cannot find function `compare_with_policy` in module `diff`
   --> src/lib.rs:226:33
error[E0425]: cannot find function `report_duplicate_spec_entries` in module `diff`
   --> src/lib.rs:230:11
error[E0425]: cannot find function `compare_storage_schemas` in module `diff`
   --> src/lib.rs:286:38
error[E0425]: cannot find function `report_unresolved_storage_references` in module `diff`
   --> src/lib.rs:295:15
error[E0063]: missing field `classification` in initializer of `Finding`
   --> src/dependency.rs:386:13
error[E0063]: missing field `classification` in initializer of `Finding`
   --> src/dependency.rs:410:21
```

`cargo check --all-targets` additionally fails on a pre-existing bug in `src/report.rs`'s `every_emitted_category_is_in_the_inventory` test: it references `literal` and `found` outside the scope where they're declared (an apparent copy/paste or merge artifact independent of the above — present verbatim in `e575dfd` too, so it predates the bad merge).

## Fix needed

A proper 3-way merge of `src/diff.rs` reconciling:
- the type-identity/event-classification split (PR #1 / `84fb5a1`)
- the storage-schema/duplicate-detection engine (`e575dfd`)

This is a substantial manual merge (~3000 lines on the storage-schema side) — not a one-line fix — since the two branches independently rewrote large, overlapping portions of the same file with little shared context for automated tooling to reconcile.

Plus a small fix to the out-of-scope `literal`/`found` variables in the `every_emitted_category_is_in_the_inventory` test in `report.rs`.

## Impact

Any PR based on current `main` will fail CI (`cargo build`, `cargo test`, `cargo clippy`) for reasons unrelated to that PR's own changes, until this is fixed.

**Comment by emmyokolo2525-cyber** [comment]
Am a full-Stack Engineer focused on frontend, backend, APIs, automation, and modern web technologies. Passionate about solving real-world problems, contributing to open source, and delivering clean, scalable, review-ready solutions.

**Comment by Anuoluwapo25** [comment]
Verified fixed as of current `main` (`0a31d27`, after PR #419 and other subsequent merges). `cargo check --all-targets` now passes cleanly on a fresh checkout.

The fix wasn't a direct patch to the bad merge — subsequent development refactored `compare_storage_schemas` (and friends) out of `diff.rs` and into a dedicated `storage_schema` module, which incidentally eliminated the broken references. The out-of-scope `literal`/`found` bug in `report.rs`'s `every_emitted_category_is_in_the_inventory` test also appears resolved (that test either changed or was removed since — `cargo check --all-targets` is clean).

Closing.
